services:
    sdeboer_data_table.factory:
        class: Sjdeboer\DataTableBundle\DataTable\DataTableFactory
        arguments:
            - '%sdeboer_data_table%'
            - '@twig'
            - '@router'
        public: true