services:
    sdeboer_data_table.factory:
        class: Sjdeboer\DataTableBundle\DataTable\DataTableFactory
        arguments:
            - '@request_stack'
            - '@doctrine'
            - '@twig'
            - '@router'
            - '%sdeboer_data_table%'
        public: true